version: '3.8'

services:
  smart-home-ui:
    build: .
    container_name: smart_home_ui
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: always
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8081:8080"  # Zigbee2MQTT Web UI
    environment:
      - TZ=Europe/Moscow
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - mosquitto
